additionalCatalogs:
  lakehouse: |
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore.metastore.svc.cluster.local:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.aws-access-key=admin
    hive.s3.aws-secret-key=password
    iceberg.register-table-procedure.enabled=true
    iceberg.unique-table-location=true
    iceberg.hive-catalog-name=minio
  minio: |
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore.metastore.svc.cluster.local:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.aws-access-key=admin
    hive.s3.aws-secret-key=password
    hive.metastore.thrift.client.connect-timeout=3m
    hive.metastore.thrift.client.read-timeout=3m
    hive.s3.connect-timeout=3m
    hive.s3.socket-timeout=3m
    hive.non-managed-table-writes-enabled=true
    hive.storage-format=ORC
    hive.allow-drop-table=true
    hive.partition-projection-enabled=true
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: trino.lakehouse.local
      paths:
        - path: /
          pathType: ImplementationSpecific
